import 'package:flutter/material.dart';
import 'package:sheba_ai/presentation/theme/color.dart';
import 'package:sheba_ai/presentation/widget/custom_button.dart';

class DisclaimerDialog extends StatelessWidget {
  final VoidCallback onAgree;

  const DisclaimerDialog({super.key, required this.onAgree});

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(16),
      ),
      title: const Text(
        textAlign: TextAlign.center,
        'Medical Disclaimer',
        style: TextStyle(
          fontWeight: FontWeight.w600,
          fontSize: 20,
        ),
      ),
      content: const SingleChildScrollView(
        child: ListBody(
          children: [
            Text(
              'Sheba.AI Prescription Analyzer is intended for informational and educational purposes only. '
              'The analysis and results generated by this app are not a substitute for professional medical advice, '
              'diagnosis, or treatment.',
              textAlign: TextAlign.justify,
              style: TextStyle(height: 1.4, ),
            ),
            SizedBox(height: 10),
            Text(
              textAlign: TextAlign.justify,
              'Always consult a qualified healthcare professional or your physician before making any medical decisions '
              'or taking any medication based on the information provided by this app.',
              style: TextStyle(height: 1.4),
            ),
            SizedBox(height: 10),
            Text(
              textAlign: TextAlign.justify,
              'If you are experiencing a medical emergency, please contact your local emergency services immediately.',
              style: TextStyle(height: 1.4, fontStyle: FontStyle.italic, fontSize: 14),
            ),
          ],
        ),
      ),
      actionsAlignment: MainAxisAlignment.spaceBetween,
      actions: [
        Row(
          children: [
            Expanded(
              child: CustomButton.secondary(
                text: 'Disagree',
                borderRadius: 32,

                textStyle: const TextStyle(fontSize: 14, fontWeight: FontWeight.normal, color: AppColors.primaryColour),
                onPressed: () {
                  Navigator.of(context).pop();
                },
              ),
            ),
            const SizedBox(width: 10),
            Expanded(
              child: CustomButton.primary(
                text: 'Agree',
                textStyle: const TextStyle(fontSize: 14, fontWeight: FontWeight.normal, color: Colors.white),
                onPressed: () {
                  Navigator.of(context).pop();
                  onAgree();
                },
              ),
            ),
          ],
        ),
      ],
    );
  }
}
